### ISSUE TITLE
Use with Exhibit Builder

### ISSUE THREAD

**Issue by AnasGhrab** [Daniel-KM/UniversalViewer4Omeka#1]
I would to know if it is possible to use the UniversalViewer4Omeka with the Exhibit Builder plugin. My main problem is that I would like to show only some pages from an item. Is the a way to indicate page numbers (from... to) ?

Thanks,

**Comment by Daniel-KM** [comment]
Hi,

The viewer is not yet included in Exhibit builder and nobody asked me to do it, so I don't work on it. 

The plugin builds a list of the files with pages in json, then the viewer load and display them. It is certainly possible to modify this list, but a field is needed to specify which file to display or not, or to create a form in the Exhibit Builder. That requires some works...

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Daniel-KM** [comment]
Hi,

The last version 2.4.1 adds a layout to display an item in exhibits. But it is not possible to specifies files.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Daniel-KM** [comment]
Hi,

The last version 2.4.2 adds a layout to display multiple items in exhibits. But it is not possible to specify files.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
