### ISSUE TITLE
Index and thumbnails tab not shown

### ISSUE THREAD

**Issue by mariobernardes** [Daniel-KM/UniversalViewer4Omeka#11]
Hello,
I have installed Omeka and Universal Viewer 2.2.2.
In the contents pane the tabs Index and Thumbnails are not shown.
For me it is very important to have an index view.
Thanks for any suggestion.

Best regards,
Mario Bernardes

**Comment by Daniel-KM** [comment]
Hi,

The thumbnail is displayed only when there are more than one image. 
The index is displayed only in the collection view (example: https://patrimoine.mines-paristech.fr/collections/play/7), but the code can be improved to set an index. Where do you save it currently? In Dublin Core Table of Contents? What format?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by mariobernardes** [comment]
He Daniel,

Thank you very much for your help.
I tried in the collection view and the tabs are shown.

Best regards,
Mario
