### ISSUE TITLE
any time I full screen, then escape to minimize, the width it returns to is wider than before

### ISSUE THREAD

**Issue by steveinbuffalolib** [Daniel-KM/UniversalViewer4Omeka#13]
Subject pretty much says it.  if I full screen then esc, it is larger than before full screen, and multiple full and escape just gets wider and wider.

**Comment by Daniel-KM** [comment]
Hi,

This is strange and the plugin is working fine in standard themes. Have you a specific theme (js and css in particular)?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by steveinbuffalolib** [comment]
I believe we are just using fall theme

http://digital.buffalolib.org/document/81

**Comment by steveinbuffalolib** [comment]
I checked – seasons theme set to fall.

**Comment by steveinbuffalolib** [comment]
I test further.. it works fine in default theme, just not with season.  It returns to a width 32% larger than it started each time.

**Comment by WaltRiceJr** [comment]
If you make the width in the plugin settings to be blank, it displays full width both before and after full screen.

**Comment by steveinbuffalolib** [comment]
That did it.  Thank you!

**Comment by Daniel-KM** [comment]
Hi,

I only added a warning in the config, because it's theme specific (javascript).

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
