### ISSUE TITLE
Not loading pre-tiled images correctly

### ISSUE THREAD

**Issue by WaltRiceJr** [Daniel-KM/UniversalViewer4Omeka#14]
When using a pre-tiled image, the UV tries to load a URL that has the server name duplicated, e.g.
`http://omeka.pahrc.nethttp//omeka.pahrc.net/files/zoom_tiles/85f5955bafd27e2018c7234589586749_zdata/TileGroup0/1-0-0.jpg`

If I comment out the $serverName piece on line 677 of ImageController.php, I can get it to work:
`'fileurl' => /* $serverUrl . */ $imageUrl,`

But I'm not sure what else this affects.

**Comment by WaltRiceJr** [comment]
A workaround for me without changing code is to make sure the "Base URL of tiles files" setting in the OpenLayersZoom plugin does not include the base url. This might break other things. 

All things equal, I would suggest that you require the OpenLayersZoom plugin setting to contain the server base name + root URI, and remove that code from the UniversalViewer plugin.

**Comment by Daniel-KM** [comment]
Hi,

I fixed the issue in OpenLayersZoom 2.7.1 and Universal Viewer 2.2.4.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
