### ISSUE TITLE
3D Object type

### ISSUE THREAD

**Issue by nikkongr** [Daniel-KM/UniversalViewer4Omeka#17]
What type of 3D object I have to use so i can use the Universal viewer as a 3d viewer?

**Comment by Daniel-KM** [comment]
Hi,

The implemented 3D format is a common one: Three.js (see http://threejs.org and https://en.wikipedia.org/wiki/Three.js ).

You can see an example of it here : http://universalviewer.io/examples/?manifest=http://files.universalviewer.io/manifests/nelis/ecorche.json. 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by nikkongr** [comment]
This is not helping me. 

Do you have any suggestion of how i can input a 3d object at omeka.

**Comment by Daniel-KM** [comment]
Hi, 

With threejs, the 3D image is represented as a json file (that you can create or convert with various tools), so you create an item with it, then the universal viewer will display it.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Daniel-KM** [comment]
Hi,

I updated the plugin (version 2.2.4) to simplify the display of 3D models. See https://github.com/Daniel-KM/UniversalViewer4Omeka#3d-models.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
