### ISSUE TITLE
Photos not uploading

### ISSUE THREAD

**Issue by danielcber** [Daniel-KM/UniversalViewer4Omeka#19]
Hi Daniel,

We are using Universal Viewer for all items and exhibits (embedded) in our Omeka collection www.coaliciondigital.org, a digital archive for ground-breaking farmworker rights organization.

Unfortunately, the Universal Viewer suddenly stopped showing our images (we had not had this issue for the better part of a year). 

I have tried uninstalling the old version and installing the new version, which did not make a difference.

I thought it might have something to do with Lightbox being installed so I erased it from all of our code, but the problem persists.

Would you have any recommendations to get our images back working on Universal Viewer?

Thank you,
Daniel Cooper Bermudez
dcooper2408@gmail.com

**Comment by Daniel-KM** [comment]
Hi,

It seems that all your items are reserved. Try to logout to see the issue as an anonymous user. This is the same for exhibits (http://coaliciondigital.org/CoalicionDigital/exhibits/show/2000marcha/2000marcha).

Furthermore, when you update a plugin, you have to check in the `/admin/plugins` page to process the upgrade of it, when needed.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by danielcber** [comment]
Hi Daniel,

The archive is a private archive for now. This is why none of the items or
exhibits are available for public viewing.
I made one item public so you can look at it:
http://coaliciondigital.org/CoalicionDigital/items/show/285

I had already updated and configured the new version of Universal Viewer.

Do you have any idea of other issues that may be affecting the viewer? It
was working fine until recently.

Warmly,
Daniel



2016-10-29 2:04 GMT-04:00 Daniel Berthereau <notifications@github.com>:

**Comment by danielcber** [comment]
This is what it looks like:
[image: Imagen integrada 1]

2016-11-03 16:24 GMT-04:00 Daniel Cooper Bermudez <dcooper2408@gmail.com>:

**Comment by Daniel-KM** [comment]
Hi,

Check with a standard theme and it will work. 

It seems that there are some spaces sent before the image. This is the same for the json: you can look it here: http://coaliciondigital.org/CoalicionDigital/image/393/info.json. For a json, this is not a problem, but no browser can display a picture that starts with blanks. Try to remove any `?>` at the end of your modified theme or something like an `echo " ";` somewhere.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by danielcber** [comment]
Hi Daniel,

The problem only applies to photos. Are there any specific files I should
be checking?

My items/show looks alright. I am not quite sure where else I can look.

Thank you for helping us through this issue.

Warmly,
Daniel

2016-11-06 16:21 GMT-04:30 Daniel Berthereau <notifications@github.com>:

**Comment by Daniel-KM** [comment]
Hi,

I see that the extension of your original images is "jpeg", not "jpg".

Could you try to upload an original image that ends with "jpg" (the standard)?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by danielcber** [comment]
Hi Daniel,

Unfortunately I have tried that and it also does not work. I have also not
been able to find any ?> or spaces such as echo " "; to remove...

Here is the items/show.php document attached. Would you mind taking a look
at it to see if there are anythings that raise flags there? Is there
anything else I can send you that would solve the problems of the spaces
within the images?

I am going to try upgrading Omeka to see if the images work after this.

Thank you for all of your help so far.

Warmly,
Daniel

2016-11-21 9:09 GMT-04:30 Daniel Berthereau <notifications@github.com>:

**Comment by Daniel-KM** [comment]
Hi,

The file is not attached.

Did you try with the default theme or with an official theme (berlin, seasons).

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by danielcber** [comment]
The website is running on a modified berlin theme.

Missed the attachment, here it is:

2016-12-07 15:01 GMT-04:30 Daniel Berthereau <notifications@github.com>:

**Comment by danielcber** [comment]
Also, I did try with the Thanks, Roy theme and we had the same problem
unfortunately.

2016-12-09 14:11 GMT-04:30 Daniel Cooper Bermudez <dcooper2408@gmail.com>:

**Comment by Daniel-KM** [comment]
Hi,

Sorry, I can't help you, this is probably related to the config of the server and I don't have access to logs.
Did you try with Apache on a test server?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Daniel-KM** [comment]
Hi,

There is a solution in https://forum.omeka.org/t/universal-viewer-not-displaying-images/3529/2: a core file was modified and not saved with a true code editor (don't use Microsoft notepad or the equivalent for Apple!).

Is it your case? Check all your files, or use git, or a fresh install of the core and plugins.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by danielcber** [comment]
Hi Daniel,

Thank you for getting back to me!

I updated Universal Viewer to the most recent version with the forced json
standards and this does not seem to be working at the moment either. Here
is the error message I get:

"Tile 0/0_0 failed to load:
http://coaliciondigital.org/CoalicionDigital/iiif-img/388/full/7,/0/default.jpg
- error: Image load aborted"  openseadragon.js:18520:9
"Tile 4/0_0 failed to load:
http://coaliciondigital.org/CoalicionDigital/iiif-img/388/full/110,/0/default.jpg
- error: Image load aborted"  openseadragon.js:18520:9

I have only used Sublime Text 3 to edit the site. I am wondering how I
would go about checking if there was an extra space at the beginning of a
file. Or perhaps I should just try a fresh install of the core and plugins
(I had done a fresh install of the core before I believe, but not of the
plug-ins).

Please let me know if you are familiar with this error? Thanks.

Warmly,
Daniel

2017-05-02 16:50 GMT-04:00 Daniel Berthereau <notifications@github.com>:

**Comment by Daniel-KM** [comment]
Hi,

On omeka.org, it was explained that a core file was changed and there were a space or a utf8 bom added at the beginning. All the files should be saved as utf8 without bom and they should start immediately with a  tag like `<?php` or something else, but not spaces. If this is not the theme, it may be a plugin or the core, or the server. You can disable all plugins except the universal viewer to see the result. 

The issue is the same for images or json files produced by the plugin: see http://coaliciondigital.org/CoalicionDigital/iiif/285/manifest.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by danielcber** [comment]
Fixed!

I deactivated the BagIt plugin and everything works like normal now!

Thank you so much for your time and dedication, it is what makes our work
possible as well.

Warmly,
Daniel

2017-05-04 6:05 GMT-04:00 Daniel Berthereau <notifications@github.com>:
