### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by jennyshk** [Daniel-KM/UniversalViewer4Omeka#20]
Hi Daniel,

I tried installing UniversalViewer4Omeka however it complains that I need "At least one graphic processor (GD or ImageMagick) is required to use the UniversalViewer." I have installed imageMagick on there already and specified the correct path in the Settings as /usr/bin. I'm not sure what I'm doing wrong. Help!

Thanks in advance,
Jenny

ERROR:
#############################
Omeka_Plugin_Exception

    At least one graphic processor (GD or ImageMagick) is required to use the UniversalViewer.

Omeka_Plugin_Exception: At least one graphic processor (GD or ImageMagick) is required to use the UniversalViewer. in /omeka/web/default/plugins/UniversalViewer/UniversalViewerPlugin.php:66
Stack trace:
#0 /omeka/web/default/application/libraries/Omeka/Plugin/Broker.php(145): UniversalViewerPlugin->hookInstall(Array)
#1 /omeka/web/default/application/libraries/Omeka/Plugin/Installer.php(130): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#2 /omeka/web/default/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
#3 /omeka/web/default/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#4 /omeka/web/default/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#5 /omeka/web/default/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /omeka/web/default/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#7 /omeka/web/default/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#8 /omeka/web/default/application/libraries/Omeka/Application.php(79): Zend_Application->run()
#9 /omeka/web/default/admin/index.php(28): Omeka_Application->run()
#10 {main}

**Comment by Daniel-KM** [comment]
Hi, 

The plugin doesn't use the command line ImageMagick, but the php modules
php-gd or php-imagick, soit you need too enable them in the config of
your server. 

Sincerely, 

Daniel Berthereau 
Infodoc & Knowledge management
