### ISSUE TITLE
Browser's native PDF viewer opens inside UV

### ISSUE THREAD

**Issue by pfabri** [Daniel-KM/UniversalViewer4Omeka#22]
Dear Daniel,

I was wondering if you could perhaps point me in the right direction with this:

## Background ##

I run an Omeka archive portal, for which I'd like to use Universal Viewer as the only viewer. I've installed the UniversalViewer plugin for Omeka, with success.

# Problem #

## Expected Behaviour ##

When the user navigates to a page which has a `.pdf` Universal Viewer (and Universal Viewer alone!) should open the pdf file.

## Actual Behaviour ##

Universal Viewer opens, and _inside it_ the browser's native pdf viewer opens as well:

![uvshot](https://cloud.githubusercontent.com/assets/16960025/21741478/21e2bd86-d4d7-11e6-83a0-9ff8b79a90bd.jpg)

## Question ##

How can I prevent the browser's pdf viewer from loading? I'd like to make all my content available for viewing online, but prevent downloading. Once the built-in pdf viewer opens, that itself always provides a download link regardless of the Universal Viewer settings.

The problem persists across multiple browsers. (Tested: Firefox and Ubuntu's built-in browser)

Please help, if you can.

Many thanks in advance!

**Comment by pfabri** [comment]
## Solved ##

Although the plugin reported that image magick was installed (or to be more precise: didn't report that it wasn't), I though all was well. But there seems to have been an issue with how it was installed, because after reinstalling it, and including it properly inside `php.ini` the above problem went away.

**Comment by pfabri** [comment]
## Spoke to soon ##


Unfortunately, after getting on with #23 and installing the `exif` extension, the problem reported there (Flash required) went away, but now the viewer opens the browser's PDF viewer _inside_ UniversalViewer again.

Does anybody have any ideas at all about how to get around this?

Many thanks,
Peter

**Comment by Daniel-KM** [comment]
Hi,

Sorry for the delay.

Universal Viewer displays the pdf when there is a single pdf. If there are readable images files plus a pdf, the images are displayed and the pdf is set as a file to download. Is it a single pdf?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by pfabri** [comment]
@Daniel-KM 
Dear Daniel,

Thanks for replying, and no problem about the delay. Having looked at all the projects you're involved in, I'm certain you are very busy.

Regarding your question, yes: it is just a single `.pdf` file, no images at all. 

Do you have any idea as to what may be causing this problem?

Many thanks in advance,
Peter

**Comment by Daniel-KM** [comment]
Hi,

When an item has a single pdf, Universal Viewer opens it with an embedded version of pdf.js. This is not the browser pdf viewer, but a specific one you can customize in /views/shared/javascripts/uv/lib/pdf.js. For more info, see the widget itself https://github.com/edsilv/UniversalViewer.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by pfabri** [comment]
Dear Daniel,

Thank you for your answer -- I can see that [the single PDF view on your examples page](http://universalviewer.io/examples/?manifest=http://wellcomelibrary.org/iiif/b17502792/manifest#?c=0&m=0&s=0&cv=0) also display the pdf.js plugin as you mentioned.

In Omeka all my files are single PDFs. Is there a way to disable downloads for them i.e. preventing pdf.js from offering a download option? 

Many thanks in advance,
Peter

**Comment by Daniel-KM** [comment]
Hi,

For the button, you can modify the file `/views/shared/javascripts/uv/lib/pdf.js` (or the pdf.min.js): see https://stackoverflow.com/questions/17547956/how-to-make-pdf-undownloadable-using-pdf-js#23619799  and /views/shared/javascripts/uv/lib/pdf.js. 

You may have to hide the button in the below bar too via config.json.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by pfabri** [comment]
Dear Daniel,

Thank you very much. This looks great. I've stumbled upon a similar thread on StackExchange previously, but this one seems more complete, especially the [GitHub conversation](https://github.com/mozilla/pdf.js/issues/2611#issuecomment-113155734) that is linked to.

**One more question:** Is there a way to activate the standard UV interface (that images and non-single PDFs use) for single PDFs too? It is so nice, and I love the page navigation. I'd much prefer to use that than pdf.js.

Many thanks!
Peter

**Comment by Daniel-KM** [comment]
Hi,

When the Universal Viewer sees a pdf, it displays it with a pdf viewer; when it sees images, it displays images... If you prefer that people sees images, you have to burst your pdf in images, then import all of them for each item. 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge managemen

**Comment by pfabri** [comment]
Dear Daniel,

Sorry for the belated response. Okay, I now fully understand. I originally thought that PDFs can also be displayed as images without converting every page into an image.

Once I converted my PDF into separate images do you know if there is a way to display them as one item inside Omeka? E.g. once I break up a 10 page long PDF into 10 separate image files have Omeka recognise them as one logical block and have it display under a single item name and have UV display it?

Many-many thanks,
Peter

**Comment by Daniel-KM** [comment]
Hi,

Don't upload one file to one item. One item can have multiple files attached. UV takes care of that.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge managemen

**Comment by pfabri** [comment]
Daniel,

I just wanted to say thanks for all your help and time making this all very clear!
