### ISSUE TITLE
Error: Adobe Flash Required

### ISSUE THREAD

**Issue by pfabri** [Daniel-KM/UniversalViewer4Omeka#23]
Dear Daniel,

Now that I solved #22 and the plugin loads without the browser's internal pdf viewer, it does not, alas, display anything, apart from the above error message.**[Edit: #22 hasn't been solved yet...]**

If, however, I try the demo on universalviewer.io, those work fine, no need for adobe flash.

What might the problem be?

Many thanks,
Peter

**Comment by Daniel-KM** [comment]
Hi,

Of course, Adobe Flash is not required. What are the mime-type and extension of files you use? Images? Sound? Video? 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by pfabri** [comment]
Hello Daniel,
No, just single `.pdf` documents, no images at all. Same content as in #22.
Many thanks,
Peter

**Comment by Daniel-KM** [comment]
Hi,

I don't find the issue. On my installs, localhost or online, it works fine with a single pdf or with images too. Do you have a public link?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
