### ISSUE TITLE
Cloudflare tile caching

### ISSUE THREAD

**Issue by edsilv** [Daniel-KM/UniversalViewer4Omeka#24]
Hi,

Firstly, thank you for making this amazing plugin. I was very happy to be able to include the UV into my Omeka project so easily.

I've done a little work today to make it easier to update the UV using gulp:

https://github.com/edsilv/UniversalViewer4Omeka/blob/master/gulpfile.js

This uses the UV dev branch, but can easily be changed in the package.json to use a release number. Let me know if you'd like me to create a PR.

I'm using Cloudflare to cache my omeka site, but have noticed that tiles from ImageController.php are not getting cached. There is a `CF-Cache-Status: MISS` header in the response.

As you can see from the ImageController.php on my fork I've tried various methods to include an Etag, Expires, and Last-Modified headers to see if this makes a difference:

https://github.com/edsilv/UniversalViewer4Omeka/blob/master/controllers/ImageController.php#L253

Unfortunately I've been unable to get the desired `CF-Cache-Status: HIT` header...

PHP/networking were never my strong suit :-) Any tips you could offer would be greatly appreciated..!

**Comment by Daniel-KM** [comment]
Hi,

Thanks, but it just a wrapper for your widget...

I think you have check the rules in CloudFlare (https://support.cloudflare.com/hc/en-us/articles/202775670) and the .htaccess of Omeka (where cache rules are disabled by default). I don' t find any other config or header (Cache-Control, Last-Modified, Expires). Are they really sent by Omeka and Apache or is it CloudFlare that doesn't want to follow them?

For the automatic update of the library, thanks, I'll include your gulp file (for the release branch).

**Comment by edsilv** [comment]
Ah, I missed the setting on the Cloudflare page rule setting Edge Cache TTL to 2 hours. Now getting a cache hit.

Here's the .htaccess setting that worked for me:

```
<filesMatch "\.(jpg|php)$">
        Header set Cache-Control "max-age=290304001, public"
</filesMatch>
```

Thanks again!
