### ISSUE TITLE
Don't seem to be able to set treeViewLeftPanel options

### ISSUE THREAD

**Issue by caosborne89** [Daniel-KM/UniversalViewer4Omeka#27]
In the the config.json there should be a property named "treeViewLeftPanel" under modules that should have options you cans set. Currently I'm trying to set "panelOpen": false, though no options seem to work.. The "moreInfoRightPanel" options seem to work just fine.

**Comment by caosborne89** [comment]
Also the "seadragonCenterPanel" module options don't seem to work either.

**Comment by Daniel-KM** [comment]
It seems to be a pure Universal Viewer issue. You can set this issue on https://github.com/UniversalViewer/UniversalViewer.

**Comment by caosborne89** [comment]
Sorry, just realized the install of UV that their documentation references is out of date.
