### ISSUE TITLE
How to make "Search within item" work? 

### ISSUE THREAD

**Issue by onwheel32** [Daniel-KM/UniversalViewer4Omeka#3]
Hello,

I have set "searchWithinEnabled" to true and enabled the searchFooterPanel module in config.json. The search box doesn't show up. How to make "Search within" work?

Thanks,

**Comment by Daniel-KM** [comment]
Hi,

I didn't check this feature, so I don't know currently how to process yet. Anyway, where are your text? In a pdf or in a metadata element?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by onwheel32** [comment]
The data is in pdf and xml (converted from pdf). I uploaded both since I don't know how the search works.

**Comment by Daniel-KM** [comment]
Hi,

If this is a pdf, you have nothing to do, the text is available directly in the pdf viewer of UniversalViewer and the pdf viewer has a search button.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by onwheel32** [comment]
The problem is the search button. It doesn't show up even if I've enabled in config.json. Is there anything else to set up to get it show up?

**Comment by Daniel-KM** [comment]
Hi,

I just check it on a fresh install of UniversalViewer and it works as is, without any modification. But the pdf should contains a layer of text, that is the case generally, except in some case. Have you try with a standard pdf, created with LibreOffice or Word? 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by m-art-in** [comment]
coming back to this question: 
Which dc-Term (or other) property should I use to ad fulltext to an image (jpg). What else is neccessary to activate the full text search in the universal viewser module?

Thanks for help
