### ISSUE TITLE
$.templates is not a function when multiple images in one item record

### ISSUE THREAD

**Issue by ianchan** [Daniel-KM/UniversalViewer4Omeka#51]
Hi,
I'm encountering the errors shown below when viewing items with multiple image files.
Example: https://together-apart.csusm.edu/omeka-classic/items/show/188
Please let me know if I can provide additional information. Thank you for your help.

VM315 uv.js:1 Uncaught Error: Mismatched anonymous define() module: function(n){return e(t,n)}
http://requirejs.org/docs/errors.html#mismatch
    at makeError (VM315 uv.js:1)
    at m (VM315 uv.js:1)
    at Object.r [as require] (VM315 uv.js:1)
    at requirejs (VM315 uv.js:1)
    at VM315 uv.js:20
makeError @ VM315 uv.js:1
m @ VM315 uv.js:1
r @ VM315 uv.js:1
requirejs @ VM315 uv.js:1
(anonymous) @ uv.js:20

VM315 uv.js:1 Uncaught Error: Mismatched anonymous define() module: function(){return a}
http://requirejs.org/docs/errors.html#mismatch
    at makeError (VM315 uv.js:1)
    at m (VM315 uv.js:1)
    at VM315 uv.js:1
makeError @ VM315 uv.js:1
m @ VM315 uv.js:1
(anonymous) @ VM315 uv.js:1
setTimeout (async)
req.nextTick @ VM315 uv.js:1
r @ VM315 uv.js:1
requirejs @ VM315 uv.js:1
(anonymous) @ VM315 uv.js:1
(anonymous) @ VM315 uv.js:1

GalleryComponent.js:97 Uncaught TypeError: $.templates is not a function
    at GalleryComponent._init (GalleryComponent.js:97)
    at new GalleryComponent (GalleryComponent.js:22)
    at t.create (VM315 uv.js:17)
    at t.e (VM315 uv.js:10)
    at t [as constructor] (VM315 uv.js:10)
    at t [as constructor] (VM315 uv.js:10)
    at new t (VM315 uv.js:17)
    at t.createModules (VM315 uv.js:19)
    at t.e.dependenciesLoaded (VM315 uv.js:11)
    at VM315 uv.js:11

**Comment by Daniel-KM** [comment]
It seems to be related to an incompatibility with another js, probably the map. Can you try without it?

**Comment by ianchan** [comment]
Sorry, I figured it out. In my theme I am loading UV for images and default file viewer for PDF. I'm using a loop and was calling UV multiple times. Ensuring it only does so once resolved the problem.

**Comment by Tyrannas** [comment]
Hi ! I'm new to Omeka (and php in general) and I'm facing the same issue, created by the same problem but have no idea how to work around. I'm trying to display two documents side by side in a custom plugin. It works well when I display the first document with 
```php
$output = get_specific_plugin_hook_output('UniversalViewer', 'public_items_show', array(
                    'record' => $item,
                    'view' => $this->view,
                ));
```

But when I do it for the second it generates the same html, with the scripts imports and generates and creates the UV in the same div. It's probably a lack of comprehension but I don't know how to fix this, if you have any advice I'll take it! Thank you
