### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by Myrav** [Daniel-KM/UniversalViewer4Omeka#6]
Hi, 

I have noticed that the Universal Viewer plugin can't handle table of contents. When we click on a chapter bookmark, the link refers to the wrong page. I checked my table of contents outside the plugin, and all of the links are ok. Is there any way to fix that bug ?

Thanks in advance and thanks for your job !

Mylène

**Comment by Daniel-KM** [comment]
Hi,

Have you a public link so I can check it?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Myrav** [comment]
I'm sorry but I work on a local server. I tried to find sites using this plugin with table of contents, but unsuccessfully.

**Comment by Daniel-KM** [comment]
Hi,

What do you mean by "table of contents"? The Dublin Core extended one? A list of items in a collection ?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Myrav** [comment]
No it is a chapter bookmark added in a PDF file. I attached an example. 

Thanks for your quick answers, 

Mylène

[BIS_00_00012_P003.zip](https://github.com/Daniel-KM/UniversalViewer4Omeka/files/377960/BIS_00_00012_P003.zip)

**Comment by Daniel-KM** [comment]
Hi,

I try it and it work fine:

![universalviewer_bookmark_pdf](https://cloud.githubusercontent.com/assets/2138485/17055662/8d7ea382-500e-11e6-88db-27aeb3febbbc.gif)

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Myrav** [comment]
Yes it displays the bookmarks but when we click on the link, it brings to the wrong page, at least for me. Maybe I did something wrong. 

Thank you very much for your answers !

Mylène

**Comment by Daniel-KM** [comment]
Hi,

Yes, there seems to be an issue, but it doesn't depend on the plugin, but on the viewer. You have to check another pdf (a standard one), and ask in https://github.com/UniversalViewer./universalviewer/issues.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Myrav** [comment]
Ok, thanks ! 

Mylène
