### ISSUE TITLE
Left panel closed by default

### ISSUE THREAD

**Issue by adehner** [Daniel-KM/UniversalViewer4Omeka#8]
Where can I set the left panel ("contents") to be closed when the viewer is loaded? I have set "leftPanelEnabled": false in config.json, but I see no changes. 

Thanks!

**Comment by Daniel-KM** [comment]
Hi,

I just check it and I don't find an issue. Do you modify the file in the plugin (`plugins/UniversalViewer/views/public/universal-viewer/config.json`)or do you copy it in the theme (`themes/My_Theme/universal-viewer/config.json`)? The most common issue is related to rights of folder and files.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by Daniel-KM** [comment]
Hi,

Furthermore, the option "leftPanelEnabled" displays or not the panel, but if you want it to be available, the option is modules/contentLeftPanel/panelOpen = false. See http://universalviewer.io/examples to get the json file with the options you want.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by adehner** [comment]
Excellent! Thank you.

**Comment by adehner** [comment]
The testing link you sent is a useful tool. However making changes to the config.json file in my Omeka installation does not change my viewer at all.

I've tried modifying the following files. But nothing happens. Are these the correct files to modify?
views/public/universal-viewer/config.json
views/shared/javascripts/uv/lib/uv-seadragon-extension.en-GB.config.json

**Comment by Daniel-KM** [comment]
Hi,

Yes, this is the files to change, even if it's better to copy them in  the theme. So you have to check rights of files and eventually the script blocker on your browser.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
